
package aplicativo.application.form.other;

/**
 *
 * @author DELL
 */
public class FormPagos extends javax.swing.JFrame {

    /**
     * Creates new form FormPagos
     */
    public FormPagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header1 = new AdminEscuela.Vista.componentes.Header();
        panelTransparent1 = new aplicativo.swing.PanelTransparent();
        jLabel5 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodEst = new javax.swing.JTextField();
        lblNombres = new javax.swing.JLabel();
        txtNomEst = new javax.swing.JTextField();
        lblFechaNa = new javax.swing.JLabel();
        btnAgregarEst = new javax.swing.JButton();
        btnEditarEst = new javax.swing.JButton();
        btnEliminarEst = new javax.swing.JButton();
        jFechaNa = new com.toedter.calendar.JDateChooser();
        lblDireccion = new javax.swing.JLabel();
        txtDireccionEst = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidosEst = new javax.swing.JTextField();
        lblSemestre = new javax.swing.JLabel();
        jComboBoxSemeEst = new javax.swing.JComboBox<>();
        scrollBarCustom1 = new aplicativo.swing.scrollbar.ScrollBarCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaMostrarEstu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel5.setText("CRUD Pagos");

        lblCodigo.setText("PagoID:");

        txtCodEst.setEnabled(false);

        lblNombres.setText("EstudianteID:");

        lblFechaNa.setText("Fecha de Pago:");

        btnAgregarEst.setText("Añadir");
        btnAgregarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEstActionPerformed(evt);
            }
        });

        btnEditarEst.setText("Editar");
        btnEditarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEstActionPerformed(evt);
            }
        });

        btnEliminarEst.setText("Eliminar");
        btnEliminarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstActionPerformed(evt);
            }
        });

        lblDireccion.setText("Estado:");

        lblApellidos.setText("Monto:");

        lblSemestre.setText("Método de pago:");

        jComboBoxSemeEst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1er Semestre ", "2do Semestre", "3ro Semestre", "4to Semestre", "5to Semestre", "6to Semestre", "7mo Semestre", "8vo Semestre", "9no Semestre", "10mo Semestre" }));

        javax.swing.GroupLayout panelTransparent1Layout = new javax.swing.GroupLayout(panelTransparent1);
        panelTransparent1.setLayout(panelTransparent1Layout);
        panelTransparent1Layout.setHorizontalGroup(
            panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollBarCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTransparent1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTransparent1Layout.createSequentialGroup()
                            .addComponent(lblSemestre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxSemeEst, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTransparent1Layout.createSequentialGroup()
                            .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(txtApellidosEst))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTransparent1Layout.createSequentialGroup()
                            .addComponent(lblFechaNa)
                            .addGap(18, 18, 18)
                            .addComponent(jFechaNa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTransparent1Layout.createSequentialGroup()
                        .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelTransparent1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarEst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditarEst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarEst))
                            .addGroup(panelTransparent1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(txtDireccionEst)
                                .addGap(69, 69, 69))))
                    .addGroup(panelTransparent1Layout.createSequentialGroup()
                        .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomEst, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodEst, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        panelTransparent1Layout.setVerticalGroup(
            panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres)
                    .addComponent(txtNomEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(txtApellidosEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFechaNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaNa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemestre)
                    .addComponent(jComboBoxSemeEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccionEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarEst)
                    .addComponent(btnEditarEst)
                    .addComponent(btnEliminarEst))
                .addGap(30, 30, 30)
                .addComponent(scrollBarCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 282, Short.MAX_VALUE))
        );

        JTablaMostrarEstu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTablaMostrarEstu.setOpaque(false);
        JTablaMostrarEstu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTablaMostrarEstuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTablaMostrarEstu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTransparent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstActionPerformed
//        int filaSeleccionada = JTablaMostrarEstu.getSelectedRow();
//
//        if (filaSeleccionada == -1) {
//            // Si no hay fila seleccionada, mostrar mensaje de advertencia
//            JOptionPane.showMessageDialog(
//                this,
//                "Por favor, seleccione un registro de la tabla para eliminar.",
//                "Advertencia",
//                JOptionPane.WARNING_MESSAGE
//            );
//        } else {
//            // Mostrar mensaje de confirmación
//            int confirmacion = JOptionPane.showConfirmDialog(
//                this,
//                "¿Está seguro de que desea eliminar este registro?",
//                "Confirmación de eliminación",
//                JOptionPane.YES_NO_OPTION,
//                JOptionPane.WARNING_MESSAGE
//            );
//
//            if (confirmacion == JOptionPane.YES_OPTION) {
//                CEstudianteDAO objEstu=new CEstudianteDAO();
//                objEstu.EliminarEstudiante(txtCodigoUsuarioLogin,txtCodEst);
//                objEstu.MostrarTablaEstudiante(JTablaMostrarEstu);
//                System.out.println("Registro eliminado.");
//            } else {
//                System.out.println("Operación cancelada.");
//                JOptionPane.showMessageDialog(this, "Operación cancelada.");
//            }
//        }
//        limpiarcampos();
    }//GEN-LAST:event_btnEliminarEstActionPerformed

    private void btnEditarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEstActionPerformed
//        CEstudianteDAO objEstu=new CEstudianteDAO();
//        objEstu.ModificarEstudiante(txtCodEst, txtNomEst, txtApellidosEst, jFechaNa, txtDNIEst, jComboBoxSemeEst, txtDireccionEst,
//            txtTelefonoEst, txtCorreoEst,lblMostrarFoto,txtFotoRuta,txtCodigoUsuarioLogin,txtContraseñaLogin);
//        objEstu.MostrarTablaEstudiante(JTablaMostrarEstu);
//        limpiarcampos();
    }//GEN-LAST:event_btnEditarEstActionPerformed

    private void btnAgregarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstActionPerformed
//        if (txtNomEst.getText().isEmpty() || txtApellidosEst.getText().isEmpty() || jFechaNa.getDateFormatString().isEmpty() || txtDNIEst.getText().isEmpty() ||
//            jComboBoxSemeEst.getSelectedItem().toString().isEmpty() || txtDireccionEst.getText().isEmpty() || txtTelefonoEst.getText().isEmpty() || txtCorreoEst.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
//        }else{
//            ModelEstudiante estudiante=new ModelEstudiante();
//            estudiante.setNombre(txtNomEst.getText());
//            estudiante.setApellido(txtApellidosEst.getText());
//            estudiante.setFechaNacimiento(jFechaNa.getDate());
//
//            String dni = txtDNIEst.getText().trim();
//            if (dni.length() == 8 && dni.matches("\\d+")) {
//                estudiante.setDni(dni);
//            } else {
//                JOptionPane.showMessageDialog(null, "El DNI debe contener exactamente 8 dígitos numéricos.");
//                return; // Salir de la función si el DNI es inválido
//            }
//            String email = txtCorreoEst.getText().trim();
//            if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$")) {
//                JOptionPane.showMessageDialog(null, "Por favor, ingrese un correo electrónico válido.");
//                return;
//            }
//            estudiante.setEmail(email);
//            estudiante.setGrado(jComboBoxSemeEst.getSelectedItem().toString());
//            estudiante.setDireccion(txtDireccionEst.getText());
//            estudiante.setTelefono(txtTelefonoEst.getText());
//            estudiante.setEmail(txtCorreoEst.getText());
//
//            try {
//                File ruta=new File(txtFotoRuta.getText());
//                byte[] icono=new byte[(int)ruta.length()];
//                InputStream input= new FileInputStream(ruta);
//                input.read(icono);
//                estudiante.setFoto(icono);
//            } catch (Exception e) {
//                estudiante.setFoto(null);
//            }
//            estudiante.setRutfo(txtFotoRuta.getText());
//
//            // Crear objeto Usuario
//            ModelUsuario usuario = new ModelUsuario();
//            usuario.setNombreUsuario(txtCodigoUsuarioLogin.getText());
//            usuario.setContraseña(new String(txtContraseñaLogin.getText()));
//            usuario.setRolID(4); // Asumamos que el rol para estudiante es 3, ajusta según tu base de datos
//            usuario.setFoto(estudiante.getFoto()); // Usar la misma foto que el estudiante
//
//            // Llamar al método de inserción
//            CEstudianteDAO objEstu = new CEstudianteDAO();
//            boolean resultado = objEstu.InsertarEstudianteYUsuario(estudiante, usuario);
//
//            if (resultado) {
//                JOptionPane.showMessageDialog(null, "Estudiante y Usuario agregados exitosamente.");
//                objEstu.MostrarTablaEstudiante(JTablaMostrarEstu);
//                limpiarcampos();
//            } else {
//                JOptionPane.showMessageDialog(null, "Error al agregar Estudiante y Usuario.");
//            }
//        }
    }//GEN-LAST:event_btnAgregarEstActionPerformed

    private void JTablaMostrarEstuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTablaMostrarEstuMouseClicked
//        CEstudianteDAO objEstu=new CEstudianteDAO();
//        objEstu.SeleccionarEstudiante(JTablaMostrarEstu, txtCodEst, txtNomEst, txtApellidosEst, jFechaNa, txtDNIEst,
//            jComboBoxSemeEst, txtDireccionEst, txtTelefonoEst, txtCorreoEst,lblMostrarFoto,txtFotoRuta,txtCodigoUsuarioLogin,txtContraseñaLogin);
    }//GEN-LAST:event_JTablaMostrarEstuMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablaMostrarEstu;
    private javax.swing.JButton btnAgregarEst;
    private javax.swing.JButton btnEditarEst;
    private javax.swing.JButton btnEliminarEst;
    private AdminEscuela.Vista.componentes.Header header1;
    private javax.swing.JComboBox<String> jComboBoxSemeEst;
    private com.toedter.calendar.JDateChooser jFechaNa;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFechaNa;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblSemestre;
    private aplicativo.swing.PanelTransparent panelTransparent1;
    private aplicativo.swing.scrollbar.ScrollBarCustom scrollBarCustom1;
    private javax.swing.JTextField txtApellidosEst;
    private javax.swing.JTextField txtCodEst;
    private javax.swing.JTextField txtDireccionEst;
    private javax.swing.JTextField txtNomEst;
    // End of variables declaration//GEN-END:variables
}
