/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplicativo.application.form.other;

/**
 *
 * @author grrrr
 */
public class FormCurso extends javax.swing.JPanel {

    /**
     * Creates new form FormCurso
     */
    public FormCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header1 = new AdminEscuela.Vista.componentes.Header();
        panelTransparent1 = new aplicativo.swing.PanelTransparent();
        jLabel5 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodCur = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNomCur = new javax.swing.JTextField();
        btnAgregarCur = new javax.swing.JButton();
        btnEditarCur = new javax.swing.JButton();
        btnEliminarCur = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaMostrarCur = new javax.swing.JTable();
        lblDescripcion = new javax.swing.JLabel();
        txtDescCur = new javax.swing.JTextField();
        scrollBarCustom1 = new aplicativo.swing.scrollbar.ScrollBarCustom();

        setPreferredSize(new java.awt.Dimension(1426, 601));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel5.setText("CRUD Curso");

        lblCodigo.setText("Codigo:");

        txtCodCur.setEnabled(false);

        lblNombre.setText("Nombre:");

        btnAgregarCur.setText("Añadir");
        btnAgregarCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCurActionPerformed(evt);
            }
        });

        btnEditarCur.setText("Editar");
        btnEditarCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCurActionPerformed(evt);
            }
        });

        btnEliminarCur.setText("Eliminar");
        btnEliminarCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCurActionPerformed(evt);
            }
        });

        JTablaMostrarCur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTablaMostrarCur.setOpaque(false);
        JTablaMostrarCur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTablaMostrarCurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTablaMostrarCur);

        lblDescripcion.setText("Descripción:");

        txtDescCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescCurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransparent1Layout = new javax.swing.GroupLayout(panelTransparent1);
        panelTransparent1.setLayout(panelTransparent1Layout);
        panelTransparent1Layout.setHorizontalGroup(
            panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent1Layout.createSequentialGroup()
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparent1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTransparent1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparent1Layout.createSequentialGroup()
                                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 25, Short.MAX_VALUE)
                                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescCur, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodCur, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomCur, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelTransparent1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnAgregarCur, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarCur, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(scrollBarCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarCur, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelTransparent1Layout.setVerticalGroup(
            panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparent1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addGap(36, 36, 36)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(38, 38, 38)
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparent1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(scrollBarCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparent1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(panelTransparent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarCur, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarCur, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarCur, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTransparent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCurActionPerformed
        if (txtNomCur.getText().isEmpty() || txtDescCur.getText().isEmpty() || jFechaNa.getDateFormatString().isEmpty() || txtDNIEst.getText().isEmpty() ||
            jComboBoxSemeEst.getSelectedItem().toString().isEmpty() || txtDireccionEst.getText().isEmpty() || txtTelefonoEst.getText().isEmpty() || txtCorreoEst.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
        }else{
            ModelEstudiante estudiante=new ModelEstudiante();
            estudiante.setNombre(txtNomCur.getText());
            estudiante.setApellido(txtDescCur.getText());
            estudiante.setFechaNacimiento(jFechaNa.getDate());

            String dni = txtDNIEst.getText().trim();
            if (dni.length() == 8 && dni.matches("\\d+")) {
                estudiante.setDni(dni);
            } else {
                JOptionPane.showMessageDialog(null, "El DNI debe contener exactamente 8 dígitos numéricos.");
                return; // Salir de la función si el DNI es inválido
            }
            String email = txtCorreoEst.getText().trim();
            if (!email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$")) {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese un correo electrónico válido.");
                return;
            }
            estudiante.setEmail(email);
            estudiante.setGrado(jComboBoxSemeEst.getSelectedItem().toString());
            estudiante.setDireccion(txtDireccionEst.getText());
            estudiante.setTelefono(txtTelefonoEst.getText());
            estudiante.setEmail(txtCorreoEst.getText());

            try {
                File ruta=new File(txtFotoRuta.getText());
                byte[] icono=new byte[(int)ruta.length()];
                InputStream input= new FileInputStream(ruta);
                input.read(icono);
                estudiante.setFoto(icono);
            } catch (Exception e) {
                estudiante.setFoto(null);
            }
            estudiante.setRutfo(txtFotoRuta.getText());

            // Crear objeto Usuario
            ModelUsuario usuario = new ModelUsuario();
            usuario.setNombreUsuario(txtCodigoUsuarioLogin.getText());
            usuario.setContraseña(new String(txtContraseñaLogin.getText()));
            usuario.setRolID(4); // Estudiante
            usuario.setFoto(estudiante.getFoto()); // Usar la misma foto que el estudiante

            // Llamar al método de inserción
            CEstudianteDAO objEstu = new CEstudianteDAO();
            boolean resultado = objEstu.InsertarEstudianteYUsuario(estudiante, usuario);

            if (resultado) {
                JOptionPane.showMessageDialog(null, "Estudiante y Usuario agregados exitosamente.");
                objEstu.MostrarTablaEstudiante(JTablaMostrarCur);
                limpiarcampos();
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar Estudiante y Usuario.");
            }
        }

    }//GEN-LAST:event_btnAgregarCurActionPerformed

    private void btnEditarCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCurActionPerformed
        CEstudianteDAO objEstu=new CEstudianteDAO();
        objEstu.ModificarEstudiante(txtCodCur, txtNomCur, txtDescCur, jFechaNa, txtDNIEst, jComboBoxSemeEst, txtDireccionEst,
            txtTelefonoEst, txtCorreoEst,lblMostrarFoto,txtFotoRuta,txtCodigoUsuarioLogin,txtContraseñaLogin);
        objEstu.MostrarTablaEstudiante(JTablaMostrarCur);
        limpiarcampos();
    }//GEN-LAST:event_btnEditarCurActionPerformed

    private void btnEliminarCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCurActionPerformed
        int filaSeleccionada = JTablaMostrarCur.getSelectedRow();

        if (filaSeleccionada == -1) {
            // Si no hay fila seleccionada, mostrar mensaje de advertencia
            JOptionPane.showMessageDialog(
                this,
                "Por favor, seleccione un registro de la tabla para eliminar.",
                "Advertencia",
                JOptionPane.WARNING_MESSAGE
            );
        } else {
            // Mostrar mensaje de confirmación
            int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea eliminar este registro?",
                "Confirmación de eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );

            if (confirmacion == JOptionPane.YES_OPTION) {
                CEstudianteDAO objEstu=new CEstudianteDAO();
                objEstu.EliminarEstudiante(txtCodigoUsuarioLogin,txtCodCur);
                objEstu.MostrarTablaEstudiante(JTablaMostrarCur);
                System.out.println("Registro eliminado.");
            } else {
                System.out.println("Operación cancelada.");
                JOptionPane.showMessageDialog(this, "Operación cancelada.");
            }
        }
        limpiarcampos();
    }//GEN-LAST:event_btnEliminarCurActionPerformed

    private void JTablaMostrarCurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTablaMostrarCurMouseClicked
        CEstudianteDAO objEstu=new CEstudianteDAO();
        objEstu.SeleccionarEstudiante(JTablaMostrarCur, txtCodCur, txtNomCur, txtDescCur, jFechaNa, txtDNIEst,
            jComboBoxSemeEst, txtDireccionEst, txtTelefonoEst, txtCorreoEst,lblMostrarFoto,txtFotoRuta,txtCodigoUsuarioLogin,txtContraseñaLogin);

    }//GEN-LAST:event_JTablaMostrarCurMouseClicked

    private void txtDescCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescCurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescCurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablaMostrarCur;
    private javax.swing.JButton btnAgregarCur;
    private javax.swing.JButton btnEditarCur;
    private javax.swing.JButton btnEliminarCur;
    private AdminEscuela.Vista.componentes.Header header1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private aplicativo.swing.PanelTransparent panelTransparent1;
    private aplicativo.swing.scrollbar.ScrollBarCustom scrollBarCustom1;
    private javax.swing.JTextField txtCodCur;
    private javax.swing.JTextField txtDescCur;
    private javax.swing.JTextField txtNomCur;
    // End of variables declaration//GEN-END:variables
}
